"""initial schema

Revision ID: 699f8673ad27
Revises: 
Create Date: 2026-06-30 16:04:53.493249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699f8673ad27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('editor', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=600), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliation_events_ts'), ['ts'], unique=True)

    op.create_table('chat_conversations',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('token_latency_ms', sa.Float(), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('conversation_cost_usd', sa.Float(), nullable=False),
    sa.Column('rag_chunks_count', sa.Integer(), nullable=False),
    sa.Column('rag_sources', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_logs_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('coauthorship_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('editor', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=600), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coauthorship_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coauthorship_events_ts'), ['ts'], unique=True)

    op.create_table('migration_state',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_hits_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_hits_ts'), ['ts'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_sub', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_hits_ts'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_hits_client_ip'))

    op.drop_table('rate_limit_hits')
    op.drop_table('migration_state')
    with op.batch_alter_table('coauthorship_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coauthorship_events_ts'))

    op.drop_table('coauthorship_events')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('chat_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_logs_user_id'))

    op.drop_table('chat_logs')
    op.drop_table('chat_conversations')
    with op.batch_alter_table('affiliation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliation_events_ts'))

    op.drop_table('affiliation_events')
    # ### end Alembic commands ###
